version: "3.9"

services:
  dh-amulets:
    image: ghcr.io/drflowerkick/dh-amulets:latest
    container_name: dh-amulets
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    environment:
      LEPTOS_SITE_ADDR: "0.0.0.0:8080"
      LEPTOS_SITE_ROOT: "site"
      RUST_LOG: "${LOGLEVEL}"
