# .github/workflows/main_pr.yml
name: CI for pushing to main branch

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    uses: ./.github/workflows/_audit.yml

  release:
    uses: ./.github/workflows/_release_please.yml